### ISSUE TITLE
Any way to plot a heatmap on top of the tiles?

### ISSUE THREAD

**Issue by juliohm** [yeesian/MapTiles.jl#1]
I wonder if it is currently possible to plot a heatmap as a layer with some transparency on the tiles? I tried the following:
```julia
using Plots; gr()
using MapTiles

plt = plot(basemap)
heatmap!(plt, lon, lat, vals, yflip=true)
```
where `lon` and `lat` are 1D vectors of size m and n, and `vals` is a vector of size `m*n`. And the lat/lon values span the same range of the basemap. This is what I am getting:

![screenshot from 2018-01-06 00-50-58](https://user-images.githubusercontent.com/3345261/34638206-b405936a-f27b-11e7-9779-e81297b5520e.png)

**Comment by yeesian** [comment]
You will need to project your coordinates from geographic (lat/lon) coordinates into tile coordinates (1:size(basemap.img,2), 1:size(basemap.img,1)).

**Comment by juliohm** [comment]
Is there any way to control the resolution of the tile so that it matches the resolution of the data array? I also tried to play with the zoom level, but it didn't change the visualization.

**Comment by juliohm** [comment]
Nevermind, the zoom level is working fine. The resolution question is valid still.

**Comment by yeesian** [comment]
Sorry, i'm not sure i understand the question

**Comment by juliohm** [comment]
Sorry, I should have explained it better. I see that we can retrieve tiles based on min/max for lat/lon. These tiles come patched as an image where the number of pixels is a function of the zoom level. My questions are:

1. Are we guaranteed to receive an image where the corners match our min/max for lat/lon or are we receiving a minimum bounding box with these coordinates inside?
2. Is there any way to specify the size in pixels of the image being retrieved?

I understand that the maps retrieved here are static images and not something like vector data that could be re-scaled without loss, but I am trying to understand how I should proceed when I have a m-by-n matrix with data (the heatmap) and a p-by-q basemap. Can we re-scale the data to be p-by-q or re-scale the basemap to be m-by-n, what do you suggest?

**Comment by juliohm** [comment]
Thanks, I tried to play with the functions defined in utils.jl but I am missing something:

```julia
using MapTiles
using Plots; gr()

minlon, maxlon = -123.5068, -121.0068
minlat, maxlat = 37.0219, 38.6885

zoomlevel = 8
maxtiles = 50
provider = MapTiles.CARTOProvider()

basemap = MapTiles.fetchmap(minlon, minlat, maxlon, maxlat, zoomlevel, provider=provider, maxtiles=maxtiles)

plt = plot(basemap)
for x in [minlon,maxlon], y in [minlat,maxlat]
    # convert corners to image coordinates
    ximg, yimg = MapTiles.lonlat2tile(x, y, zoomlevel)

    # add red dots at corners of the map
    scatter!(plt, [ximg], [yimg], c="red")
end
plt
```
![screenshot from 2018-01-06 18-35-51](https://user-images.githubusercontent.com/3345261/34645957-74dfa906-f310-11e7-8bb0-808623a857d6.png)

**Comment by yeesian** [comment]
Yeah, you're not likely to get exactly what you ask for, since raster tiles are "pre-baked". It involves a process of [rounding](https://github.com/yeesian/MapTiles.jl/blob/master/src/utils.jl#L23-L27) and [correction](https://github.com/yeesian/MapTiles.jl/blob/master/src/utils.jl#L53-L59). It's mostly based on [this PR in smopy](https://github.com/rossant/smopy/pull/8)

**Comment by juliohm** [comment]
But there is no way to just convert lat/lon values to pixel coordinates as described in the smopy README? It seems like the first thing one would like to do after putting the basemap on a display. :)

**Comment by yeesian** [comment]
> But there is no way to just convert lat/lon values to pixel coordinates as described in the smopy README?

https://github.com/yeesian/MapTiles.jl/blob/master/src/utils.jl#L38-L41

**Comment by juliohm** [comment]
Awesome, it is getting closer :) I will play around the the heatmap data now to see if it is placed in the correct place.

**Comment by juliohm** [comment]
And there we go, the heatmap is placed properly now \o/

![screenshot from 2018-01-06 19-39-55](https://user-images.githubusercontent.com/3345261/34646315-7c99f238-f319-11e7-9f30-f518d02de339.png)

The only issue I am having seems disconnected from MapTiles.jl, the transparency of the heatmap command in plots is not working.

**Comment by juliohm** [comment]
Thanks for the help Yeesian, I will close the issue. Please let me know if an example like this would be interesting for the README, I could submit a PR.

**Comment by yeesian** [comment]
My pleasure! Do file an issue in the Plots.jl package for the heatmap alpha; I think they have a similar issue with their contour plots too.

I'm not sure I'm ready to start document this package yet, but a notebook/gist with the example will be very nice! I'll be happy to link to it, and it'll be a helpful reference to me if I need to source for examples.
