### ISSUE TITLE
Interactive UI for displaying map

### ISSUE THREAD

**Issue by scls19fr** [yeesian/MapTiles.jl#14]
Hello,

I wonder if there is currently a way to have with Julia an interactive user interface for interacting with web map tiles ie a way to zoom in / zoom out / pan.

If such a solution currently exists maybe it could be documented in https://github.com/yeesian/MapTiles.jl/issues/6#issuecomment-773102290

Kind regards

**Comment by yeesian** [comment]
> I wonder if there is currently a way to have with Julia an interactive user interface for interacting with web map tiles ie a way to zoom in / zoom out / pan.

Hi, I'm afraid the primary focus of this package will be on fetching map data/tiles, rather than being a full-fletched app. It might be possible for someone else to implement something that works via https://github.com/JuliaPlots/GeoMakie.jl, but that is a non-goal for this package.
