### ISSUE TITLE
use

### ISSUE THREAD

**Issue by mkborregaard** [yeesian/MapTiles.jl#6]
Hey,
this looks cool. 
1. Do you need help getting this on 1.0?
2. Are there any examples of use?

**Comment by yeesian** [comment]
Yes (for 1) and no (for 2), haha. I've just been using it for my own research so far, and haven't had the time to turn it into a professional package yet.

The only example of usage so far is in [this comment](https://github.com/yeesian/MapTiles.jl/issues/1#issuecomment-355794445) (and corresponding [blogpost](https://juliohm.github.io/science/california-earthquake/)), but it is not documented yet.

**Comment by mkborregaard** [comment]
Great, thanks! Do you not have femtocleaner turned on? Otherwise I don't mind taking a stab at it once I have a moment.

**Comment by yeesian** [comment]
> Do you not have femtocleaner turned on? Otherwise I don't mind taking a stab at it once I have a moment.

Thanks! I have just installed it for this repository and opened #7 for it.

**Comment by scls19fr** [comment]
Having a minimal documentation will be great!

Maybe you can set up a very minimal [Documenter.jl](https://github.com/JuliaDocs/Documenter.jl) configuration with CI builds to publish doc to Github page and hope to have contributors to improve doc.

I'm also wondering if moving this package to https://github.com/JuliaGeo won't give it more highlight... and so more contributors.

Maybe we could (at least) discuss here for a plan for documentation.

1. Installation
2. Displaying map 
  a. Displaying map from buildin mapsource providers
  b. Displaying map from custom mapsource providers
3. Improving map with data
  a. Adding points to map
  b. Drawing on a map
  c. Heatmap on top of a map
4. Others useful Julia libraries to deal with maps and geographical data
4. API description

**Comment by scls19fr** [comment]
An other (simpler) option for documenting this package could be to simply use [Github wiki](https://github.com/yeesian/MapTiles.jl/wiki) which supports markdown syntax.

https://docs.github.com/en/github/building-a-strong-community/documenting-your-project-with-wikis

**Comment by yeesian** [comment]
Thanks for taking a stab at documentation structure in https://github.com/yeesian/MapTiles.jl/issues/6#issuecomment-773102290! I'll be happy to review a PR for it :)

For an initial attempt at improving the documentation, I think we can (i) keep it to the README for now and move to Documenter only if it starts to become a lot more fleshed out as a package, and (ii) keep sections 3 and 4 of https://github.com/yeesian/MapTiles.jl/issues/6#issuecomment-773102290 optional.
